@startuml
' Mengatur layout diagram agar memanjang ke bawah dan lebar tetap proporsional
' Ini membantu diagram agar tidak terlalu lebar, cocok untuk ukuran kertas A4 potret
left to right direction

skinparam dpi 200
skinparam page {
  orientation portrait
  margin 10
}
skinparam maxClassWidth 150
skinparam nodesep 15
skinparam ranksep 30

skinparam linetype ortho

skinparam class {
  BackgroundColor #F8F9FA
  BorderColor #6C757D
  FontSize 10
}
skinparam arrow {
  FontSize 8
}

' Deklarasi Kelas
class UserAccount
class AuthController
class AuthService
class PasswordHasher
class Session
class EmailService
class OtpService
class OtpCode
class RegistrationView
class LoginView
class ResetPasswordView

class FinancialProfile
class FinancialAccount
class Category
class IncomeSource
class ExpensePlan
class BillingCycle
class ProfileController
class ProfileService
class ProfileForm

class Transaction
class TransactionController
class TransactionService
class TransactionForm

class ReportController
class ReportService
class ReportView

class Notification
class NotificationManager
class NotificationService

class Alert
class AlertManager
class AlertService

' Hubungan Antar Kelas
AuthController -> AuthService
AuthController ..> OtpService
AuthController ..> EmailService
AuthController ..> RegistrationView
AuthController ..> LoginView
AuthController ..> ResetPasswordView

AuthService ..> PasswordHasher
AuthService -> UserAccount

OtpService -> OtpCode
AuthController ..> PasswordHasher
AuthController ..> Session

UserAccount "1" -- "0..*" Session

FinancialProfile *-- "1..*" FinancialAccount
FinancialProfile *-- "1..*" Category
FinancialProfile *-- "0..*" IncomeSource
FinancialProfile *-- "0..*" ExpensePlan

IncomeSource --> Category
ExpensePlan  --> Category
IncomeSource --> FinancialAccount
ExpensePlan  --> FinancialAccount
ExpensePlan  --> BillingCycle

ProfileController --> ProfileService
ProfileController ..> ProfileForm
ProfileService --> FinancialProfile

TransactionForm ..> TransactionController

TransactionController ..> TransactionService

TransactionService ..> Transaction
TransactionService ..> FinancialAccount
TransactionService ..> Category

Transaction "0..*" -- "1" FinancialAccount
Transaction "0..*" -- "1" Category 

ReportView ..> ReportController

ReportController ..> ReportService

ReportService ..> Transaction
ReportService ..> FinancialAccount 
ReportService ..> Category
ReportService ..> FinancialProfile

NotificationManager --> Notification : "manages"
NotificationManager --> NotificationService : "uses"
NotificationService --> Notification : "sends"

@enduml
